nodemock = require 'nodemock'

module.exports = class Freshbooks
  constructor: (base_uri, api_token) ->

  Task: class Task
    constructor: ->
      return nodemock
        .mock('list')
        .takes (err, tasks) ->
          tasks
        .calls(0, [
          undefined, [
            {
              task_id: '1',
              rate: 99.99
              name: 'Simulated task',
              description: 'A task generated by nodemock'
            }
          ]
        ])
