.TH "FRESHBOOKS\-TASK" "" "November 2013" "" ""
.SH "NAME"
\fBfreshbooks-task\fR
.QP
.P
A command\-line interface for interacting with Freshbooks Tasks

.
.SH Usage
.P
.RS 2
.EX
\-\-list, \-l \- Display the full list of tasks
\-\-help, \-h \- Display this message
.EE
.RE
.SH Examples
.P
.RS 2
.EX
# Executing task with no options
$ freshbooks\-task
.EE
.RE