(function() {
  var Freshbooks, nodemock;

  nodemock = require('nodemock');

  module.exports = Freshbooks = (function() {
    var Task;

    function Freshbooks(base_uri, api_token) {}

    Freshbooks.prototype.Task = Task = (function() {
      function Task() {
        return nodemock.mock('list').takes(function(err, tasks) {
          return tasks;
        }).calls(0, [
          void 0, [
            {
              task_id: '1',
              rate: 99.99,
              name: 'Simulated task',
              description: 'A task generated by nodemock'
            }
          ]
        ]);
      }

      return Task;

    })();

    return Freshbooks;

  })();

}).call(this);
